<main class="container py-5">
    <?php require "controllers/get-user.php" ?>
    <a href="index.php?route=list">Retour à la liste</a>
    <h1 class="my-5">Modifier un utilisateur</h1>
    <form method="post" action="controllers/update-user.php">
        <fieldset class="form-group mb-2">
            <label class="form-label" for="user-id">Id</label>
            <input class="form-control" type="text" name="user-id" id="user-id" value=<?= $user['id'] ?> readonly required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="name">Nom</label>
            <input class="form-control" type="text" name="name" id="name" value=<?= $user['username'] ?> required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="email">Email</label>
            <input class="form-control" type="email" name="email" id="email" value=<?= $user['email'] ?> required>
        </fieldset>
        <fieldset class="form-group mb-5">
            <label class="form-label" for="job">Emploi</label>
            <select class="form-select" id="job" name="job">
                
                <option value="" <?= ($user['job'] == null || $user['job'] == 0) ? 'selected' : '' ?>>Sélectionnez l'emploi</option>
                
                <option value="1" <?= $user['job'] == 1 ? 'selected' : '' ?>>Journaliste</option>
                <option value="2" <?= $user['job'] == 2 ? 'selected' : '' ?>>Conservatrice de musée</option>
                <option value="3" <?= $user['job'] == 3 ? 'selected' : '' ?>>Riche</option>
                <option value="4" <?= $user['job'] == 4 ? 'selected' : '' ?>>Vétéran</option>
                <option value="5" <?= $user['job'] == 5 ? 'selected' : '' ?>>Lycéen</option>
            </select>
        </fieldset>
        <fieldset class="form-group">
            <button class="btn btn-primary" type="submit">Enregistrer</button>
        </fieldset>
    </form>
</main>