<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Exercice Controllers et Affichage</title>
        <link rel="stylesheet" href="http://localhost/Projets/coda-bph-all/coda-bph-j8/affichage/assets/css/style.css" />
    </head>
    <body>
        <header>
            <h1>Neon Blog</h1>
        </header>
        <?php
            require_once "config/autoload.php";
            require "templates/$template.phtml";
        ?>
        <footer>
            <p>The Neon Blog 2025 - 2026</p>
        </footer>
    </body>
</html>